const { DataTypes } = require('sequelize');

module.exports = shiftEntrytMstModel;

function shiftEntrytMstModel(sequelize) {
    const attributes = {
        RID: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
        ShiftDate: { type: DataTypes.STRING(30) },
        Department: { type: DataTypes.STRING },
        MIn: {type: DataTypes.TIME },
        MOut: {type: DataTypes.TIME },
        MOTIn: {type: DataTypes.TIME },
        MOTOut: {type: DataTypes.TIME },
        EIn: {type: DataTypes.TIME },
        EOut: {type: DataTypes.TIME },
        EOTIn: {type: DataTypes.TIME },
        EOTOut: {type: DataTypes.TIME },
        HalfIn: {type: DataTypes.TIME },
        HalfOut: {type: DataTypes.TIME },
        Late: {type: DataTypes.TIME },
        LunchIn: {type: DataTypes.TIME },
        LunchOut: {type: DataTypes.TIME },
        Sflag: { type: DataTypes.CHAR(1), allowNull: true },
        SDate: { type: DataTypes.STRING, allowNull: true },
        LogID: { type: DataTypes.INTEGER, allowNull: true },
        PcID: { type: DataTypes.STRING(20), allowNull: true },
        Ever: { type: DataTypes.INTEGER, allowNull: true },
        CompanyCode: { type: DataTypes.INTEGER, allowNull: true },
        SortId: { type: DataTypes.INTEGER, allowNull: true },
        Active: { type: DataTypes.BOOLEAN, allowNull: true },
        AutoGenerated: { type: DataTypes.BOOLEAN, allowNull: true },
        IsDelete: { type: DataTypes.BOOLEAN, allowNull: true },
    };

    // const options = {
    //     defaultScope: {
    //         // exclude password and Token by default
    //         attributes: { exclude: ['Password', 'Token'] }
    //     },
    //     scopes: {
    //         // include hash with this scope
    //         withHash: { attributes: {exclude: ['Token']}, },
    //         withToken: { attributes: {exclude: ['Password']}, },
    //         withAll: { attributes: {}, }

    //     }
    // };

    return sequelize.define('ShiftEntrytMst', attributes, {
        tableName: 'ShiftEntrytMst', // Explicitly set the table name
        timestamps: false,
    });
}  